default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_name_development
  username: your_db_username
  password: your_db_password

test:
  <<: *default
  database: your_app_name_test
  username: your_db_username
  password: your_db_password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
